// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/account"
	"github.com/Wei-Shaw/sub2api/ent/group"
	"github.com/Wei-Shaw/sub2api/ent/packagechannel"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// PackageChannelUpdate is the builder for updating PackageChannel entities.
type PackageChannelUpdate struct {
	config
	hooks    []Hook
	mutation *PackageChannelMutation
}

// Where appends a list predicates to the PackageChannelUpdate builder.
func (_u *PackageChannelUpdate) Where(ps ...predicate.PackageChannel) *PackageChannelUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PackageChannelUpdate) SetUpdatedAt(v time.Time) *PackageChannelUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *PackageChannelUpdate) SetGroupID(v int64) *PackageChannelUpdate {
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *PackageChannelUpdate) SetNillableGroupID(v *int64) *PackageChannelUpdate {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *PackageChannelUpdate) SetAccountID(v int64) *PackageChannelUpdate {
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *PackageChannelUpdate) SetNillableAccountID(v *int64) *PackageChannelUpdate {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// SetWeight sets the "weight" field.
func (_u *PackageChannelUpdate) SetWeight(v int) *PackageChannelUpdate {
	_u.mutation.ResetWeight()
	_u.mutation.SetWeight(v)
	return _u
}

// SetNillableWeight sets the "weight" field if the given value is not nil.
func (_u *PackageChannelUpdate) SetNillableWeight(v *int) *PackageChannelUpdate {
	if v != nil {
		_u.SetWeight(*v)
	}
	return _u
}

// AddWeight adds value to the "weight" field.
func (_u *PackageChannelUpdate) AddWeight(v int) *PackageChannelUpdate {
	_u.mutation.AddWeight(v)
	return _u
}

// SetMaxUsers sets the "max_users" field.
func (_u *PackageChannelUpdate) SetMaxUsers(v int) *PackageChannelUpdate {
	_u.mutation.ResetMaxUsers()
	_u.mutation.SetMaxUsers(v)
	return _u
}

// SetNillableMaxUsers sets the "max_users" field if the given value is not nil.
func (_u *PackageChannelUpdate) SetNillableMaxUsers(v *int) *PackageChannelUpdate {
	if v != nil {
		_u.SetMaxUsers(*v)
	}
	return _u
}

// AddMaxUsers adds value to the "max_users" field.
func (_u *PackageChannelUpdate) AddMaxUsers(v int) *PackageChannelUpdate {
	_u.mutation.AddMaxUsers(v)
	return _u
}

// SetIsEnabled sets the "is_enabled" field.
func (_u *PackageChannelUpdate) SetIsEnabled(v bool) *PackageChannelUpdate {
	_u.mutation.SetIsEnabled(v)
	return _u
}

// SetNillableIsEnabled sets the "is_enabled" field if the given value is not nil.
func (_u *PackageChannelUpdate) SetNillableIsEnabled(v *bool) *PackageChannelUpdate {
	if v != nil {
		_u.SetIsEnabled(*v)
	}
	return _u
}

// SetGroup sets the "group" edge to the Group entity.
func (_u *PackageChannelUpdate) SetGroup(v *Group) *PackageChannelUpdate {
	return _u.SetGroupID(v.ID)
}

// SetAccount sets the "account" edge to the Account entity.
func (_u *PackageChannelUpdate) SetAccount(v *Account) *PackageChannelUpdate {
	return _u.SetAccountID(v.ID)
}

// Mutation returns the PackageChannelMutation object of the builder.
func (_u *PackageChannelUpdate) Mutation() *PackageChannelMutation {
	return _u.mutation
}

// ClearGroup clears the "group" edge to the Group entity.
func (_u *PackageChannelUpdate) ClearGroup() *PackageChannelUpdate {
	_u.mutation.ClearGroup()
	return _u
}

// ClearAccount clears the "account" edge to the Account entity.
func (_u *PackageChannelUpdate) ClearAccount() *PackageChannelUpdate {
	_u.mutation.ClearAccount()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PackageChannelUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PackageChannelUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PackageChannelUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PackageChannelUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PackageChannelUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := packagechannel.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PackageChannelUpdate) check() error {
	if _u.mutation.GroupCleared() && len(_u.mutation.GroupIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PackageChannel.group"`)
	}
	if _u.mutation.AccountCleared() && len(_u.mutation.AccountIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PackageChannel.account"`)
	}
	return nil
}

func (_u *PackageChannelUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(packagechannel.Table, packagechannel.Columns, sqlgraph.NewFieldSpec(packagechannel.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(packagechannel.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Weight(); ok {
		_spec.SetField(packagechannel.FieldWeight, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedWeight(); ok {
		_spec.AddField(packagechannel.FieldWeight, field.TypeInt, value)
	}
	if value, ok := _u.mutation.MaxUsers(); ok {
		_spec.SetField(packagechannel.FieldMaxUsers, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMaxUsers(); ok {
		_spec.AddField(packagechannel.FieldMaxUsers, field.TypeInt, value)
	}
	if value, ok := _u.mutation.IsEnabled(); ok {
		_spec.SetField(packagechannel.FieldIsEnabled, field.TypeBool, value)
	}
	if _u.mutation.GroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   packagechannel.GroupTable,
			Columns: []string{packagechannel.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   packagechannel.GroupTable,
			Columns: []string{packagechannel.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AccountCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   packagechannel.AccountTable,
			Columns: []string{packagechannel.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   packagechannel.AccountTable,
			Columns: []string{packagechannel.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{packagechannel.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PackageChannelUpdateOne is the builder for updating a single PackageChannel entity.
type PackageChannelUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PackageChannelMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PackageChannelUpdateOne) SetUpdatedAt(v time.Time) *PackageChannelUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetGroupID sets the "group_id" field.
func (_u *PackageChannelUpdateOne) SetGroupID(v int64) *PackageChannelUpdateOne {
	_u.mutation.SetGroupID(v)
	return _u
}

// SetNillableGroupID sets the "group_id" field if the given value is not nil.
func (_u *PackageChannelUpdateOne) SetNillableGroupID(v *int64) *PackageChannelUpdateOne {
	if v != nil {
		_u.SetGroupID(*v)
	}
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *PackageChannelUpdateOne) SetAccountID(v int64) *PackageChannelUpdateOne {
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *PackageChannelUpdateOne) SetNillableAccountID(v *int64) *PackageChannelUpdateOne {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// SetWeight sets the "weight" field.
func (_u *PackageChannelUpdateOne) SetWeight(v int) *PackageChannelUpdateOne {
	_u.mutation.ResetWeight()
	_u.mutation.SetWeight(v)
	return _u
}

// SetNillableWeight sets the "weight" field if the given value is not nil.
func (_u *PackageChannelUpdateOne) SetNillableWeight(v *int) *PackageChannelUpdateOne {
	if v != nil {
		_u.SetWeight(*v)
	}
	return _u
}

// AddWeight adds value to the "weight" field.
func (_u *PackageChannelUpdateOne) AddWeight(v int) *PackageChannelUpdateOne {
	_u.mutation.AddWeight(v)
	return _u
}

// SetMaxUsers sets the "max_users" field.
func (_u *PackageChannelUpdateOne) SetMaxUsers(v int) *PackageChannelUpdateOne {
	_u.mutation.ResetMaxUsers()
	_u.mutation.SetMaxUsers(v)
	return _u
}

// SetNillableMaxUsers sets the "max_users" field if the given value is not nil.
func (_u *PackageChannelUpdateOne) SetNillableMaxUsers(v *int) *PackageChannelUpdateOne {
	if v != nil {
		_u.SetMaxUsers(*v)
	}
	return _u
}

// AddMaxUsers adds value to the "max_users" field.
func (_u *PackageChannelUpdateOne) AddMaxUsers(v int) *PackageChannelUpdateOne {
	_u.mutation.AddMaxUsers(v)
	return _u
}

// SetIsEnabled sets the "is_enabled" field.
func (_u *PackageChannelUpdateOne) SetIsEnabled(v bool) *PackageChannelUpdateOne {
	_u.mutation.SetIsEnabled(v)
	return _u
}

// SetNillableIsEnabled sets the "is_enabled" field if the given value is not nil.
func (_u *PackageChannelUpdateOne) SetNillableIsEnabled(v *bool) *PackageChannelUpdateOne {
	if v != nil {
		_u.SetIsEnabled(*v)
	}
	return _u
}

// SetGroup sets the "group" edge to the Group entity.
func (_u *PackageChannelUpdateOne) SetGroup(v *Group) *PackageChannelUpdateOne {
	return _u.SetGroupID(v.ID)
}

// SetAccount sets the "account" edge to the Account entity.
func (_u *PackageChannelUpdateOne) SetAccount(v *Account) *PackageChannelUpdateOne {
	return _u.SetAccountID(v.ID)
}

// Mutation returns the PackageChannelMutation object of the builder.
func (_u *PackageChannelUpdateOne) Mutation() *PackageChannelMutation {
	return _u.mutation
}

// ClearGroup clears the "group" edge to the Group entity.
func (_u *PackageChannelUpdateOne) ClearGroup() *PackageChannelUpdateOne {
	_u.mutation.ClearGroup()
	return _u
}

// ClearAccount clears the "account" edge to the Account entity.
func (_u *PackageChannelUpdateOne) ClearAccount() *PackageChannelUpdateOne {
	_u.mutation.ClearAccount()
	return _u
}

// Where appends a list predicates to the PackageChannelUpdate builder.
func (_u *PackageChannelUpdateOne) Where(ps ...predicate.PackageChannel) *PackageChannelUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PackageChannelUpdateOne) Select(field string, fields ...string) *PackageChannelUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated PackageChannel entity.
func (_u *PackageChannelUpdateOne) Save(ctx context.Context) (*PackageChannel, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PackageChannelUpdateOne) SaveX(ctx context.Context) *PackageChannel {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PackageChannelUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PackageChannelUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PackageChannelUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := packagechannel.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PackageChannelUpdateOne) check() error {
	if _u.mutation.GroupCleared() && len(_u.mutation.GroupIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PackageChannel.group"`)
	}
	if _u.mutation.AccountCleared() && len(_u.mutation.AccountIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PackageChannel.account"`)
	}
	return nil
}

func (_u *PackageChannelUpdateOne) sqlSave(ctx context.Context) (_node *PackageChannel, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(packagechannel.Table, packagechannel.Columns, sqlgraph.NewFieldSpec(packagechannel.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "PackageChannel.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, packagechannel.FieldID)
		for _, f := range fields {
			if !packagechannel.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != packagechannel.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(packagechannel.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Weight(); ok {
		_spec.SetField(packagechannel.FieldWeight, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedWeight(); ok {
		_spec.AddField(packagechannel.FieldWeight, field.TypeInt, value)
	}
	if value, ok := _u.mutation.MaxUsers(); ok {
		_spec.SetField(packagechannel.FieldMaxUsers, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMaxUsers(); ok {
		_spec.AddField(packagechannel.FieldMaxUsers, field.TypeInt, value)
	}
	if value, ok := _u.mutation.IsEnabled(); ok {
		_spec.SetField(packagechannel.FieldIsEnabled, field.TypeBool, value)
	}
	if _u.mutation.GroupCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   packagechannel.GroupTable,
			Columns: []string{packagechannel.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   packagechannel.GroupTable,
			Columns: []string{packagechannel.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AccountCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   packagechannel.AccountTable,
			Columns: []string{packagechannel.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   packagechannel.AccountTable,
			Columns: []string{packagechannel.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &PackageChannel{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{packagechannel.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
