// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/account"
	"github.com/Wei-Shaw/sub2api/ent/group"
	"github.com/Wei-Shaw/sub2api/ent/packagechannel"
)

// PackageChannelCreate is the builder for creating a PackageChannel entity.
type PackageChannelCreate struct {
	config
	mutation *PackageChannelMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *PackageChannelCreate) SetCreatedAt(v time.Time) *PackageChannelCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *PackageChannelCreate) SetNillableCreatedAt(v *time.Time) *PackageChannelCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *PackageChannelCreate) SetUpdatedAt(v time.Time) *PackageChannelCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *PackageChannelCreate) SetNillableUpdatedAt(v *time.Time) *PackageChannelCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetGroupID sets the "group_id" field.
func (_c *PackageChannelCreate) SetGroupID(v int64) *PackageChannelCreate {
	_c.mutation.SetGroupID(v)
	return _c
}

// SetAccountID sets the "account_id" field.
func (_c *PackageChannelCreate) SetAccountID(v int64) *PackageChannelCreate {
	_c.mutation.SetAccountID(v)
	return _c
}

// SetWeight sets the "weight" field.
func (_c *PackageChannelCreate) SetWeight(v int) *PackageChannelCreate {
	_c.mutation.SetWeight(v)
	return _c
}

// SetNillableWeight sets the "weight" field if the given value is not nil.
func (_c *PackageChannelCreate) SetNillableWeight(v *int) *PackageChannelCreate {
	if v != nil {
		_c.SetWeight(*v)
	}
	return _c
}

// SetMaxUsers sets the "max_users" field.
func (_c *PackageChannelCreate) SetMaxUsers(v int) *PackageChannelCreate {
	_c.mutation.SetMaxUsers(v)
	return _c
}

// SetNillableMaxUsers sets the "max_users" field if the given value is not nil.
func (_c *PackageChannelCreate) SetNillableMaxUsers(v *int) *PackageChannelCreate {
	if v != nil {
		_c.SetMaxUsers(*v)
	}
	return _c
}

// SetIsEnabled sets the "is_enabled" field.
func (_c *PackageChannelCreate) SetIsEnabled(v bool) *PackageChannelCreate {
	_c.mutation.SetIsEnabled(v)
	return _c
}

// SetNillableIsEnabled sets the "is_enabled" field if the given value is not nil.
func (_c *PackageChannelCreate) SetNillableIsEnabled(v *bool) *PackageChannelCreate {
	if v != nil {
		_c.SetIsEnabled(*v)
	}
	return _c
}

// SetGroup sets the "group" edge to the Group entity.
func (_c *PackageChannelCreate) SetGroup(v *Group) *PackageChannelCreate {
	return _c.SetGroupID(v.ID)
}

// SetAccount sets the "account" edge to the Account entity.
func (_c *PackageChannelCreate) SetAccount(v *Account) *PackageChannelCreate {
	return _c.SetAccountID(v.ID)
}

// Mutation returns the PackageChannelMutation object of the builder.
func (_c *PackageChannelCreate) Mutation() *PackageChannelMutation {
	return _c.mutation
}

// Save creates the PackageChannel in the database.
func (_c *PackageChannelCreate) Save(ctx context.Context) (*PackageChannel, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PackageChannelCreate) SaveX(ctx context.Context) *PackageChannel {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PackageChannelCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PackageChannelCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PackageChannelCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := packagechannel.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := packagechannel.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Weight(); !ok {
		v := packagechannel.DefaultWeight
		_c.mutation.SetWeight(v)
	}
	if _, ok := _c.mutation.MaxUsers(); !ok {
		v := packagechannel.DefaultMaxUsers
		_c.mutation.SetMaxUsers(v)
	}
	if _, ok := _c.mutation.IsEnabled(); !ok {
		v := packagechannel.DefaultIsEnabled
		_c.mutation.SetIsEnabled(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PackageChannelCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "PackageChannel.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "PackageChannel.updated_at"`)}
	}
	if _, ok := _c.mutation.GroupID(); !ok {
		return &ValidationError{Name: "group_id", err: errors.New(`ent: missing required field "PackageChannel.group_id"`)}
	}
	if _, ok := _c.mutation.AccountID(); !ok {
		return &ValidationError{Name: "account_id", err: errors.New(`ent: missing required field "PackageChannel.account_id"`)}
	}
	if _, ok := _c.mutation.Weight(); !ok {
		return &ValidationError{Name: "weight", err: errors.New(`ent: missing required field "PackageChannel.weight"`)}
	}
	if _, ok := _c.mutation.MaxUsers(); !ok {
		return &ValidationError{Name: "max_users", err: errors.New(`ent: missing required field "PackageChannel.max_users"`)}
	}
	if _, ok := _c.mutation.IsEnabled(); !ok {
		return &ValidationError{Name: "is_enabled", err: errors.New(`ent: missing required field "PackageChannel.is_enabled"`)}
	}
	if len(_c.mutation.GroupIDs()) == 0 {
		return &ValidationError{Name: "group", err: errors.New(`ent: missing required edge "PackageChannel.group"`)}
	}
	if len(_c.mutation.AccountIDs()) == 0 {
		return &ValidationError{Name: "account", err: errors.New(`ent: missing required edge "PackageChannel.account"`)}
	}
	return nil
}

func (_c *PackageChannelCreate) sqlSave(ctx context.Context) (*PackageChannel, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PackageChannelCreate) createSpec() (*PackageChannel, *sqlgraph.CreateSpec) {
	var (
		_node = &PackageChannel{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(packagechannel.Table, sqlgraph.NewFieldSpec(packagechannel.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(packagechannel.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(packagechannel.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Weight(); ok {
		_spec.SetField(packagechannel.FieldWeight, field.TypeInt, value)
		_node.Weight = value
	}
	if value, ok := _c.mutation.MaxUsers(); ok {
		_spec.SetField(packagechannel.FieldMaxUsers, field.TypeInt, value)
		_node.MaxUsers = value
	}
	if value, ok := _c.mutation.IsEnabled(); ok {
		_spec.SetField(packagechannel.FieldIsEnabled, field.TypeBool, value)
		_node.IsEnabled = value
	}
	if nodes := _c.mutation.GroupIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   packagechannel.GroupTable,
			Columns: []string{packagechannel.GroupColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(group.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.GroupID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.AccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   packagechannel.AccountTable,
			Columns: []string{packagechannel.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.AccountID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.PackageChannel.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PackageChannelUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *PackageChannelCreate) OnConflict(opts ...sql.ConflictOption) *PackageChannelUpsertOne {
	_c.conflict = opts
	return &PackageChannelUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.PackageChannel.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *PackageChannelCreate) OnConflictColumns(columns ...string) *PackageChannelUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &PackageChannelUpsertOne{
		create: _c,
	}
}

type (
	// PackageChannelUpsertOne is the builder for "upsert"-ing
	//  one PackageChannel node.
	PackageChannelUpsertOne struct {
		create *PackageChannelCreate
	}

	// PackageChannelUpsert is the "OnConflict" setter.
	PackageChannelUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *PackageChannelUpsert) SetUpdatedAt(v time.Time) *PackageChannelUpsert {
	u.Set(packagechannel.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PackageChannelUpsert) UpdateUpdatedAt() *PackageChannelUpsert {
	u.SetExcluded(packagechannel.FieldUpdatedAt)
	return u
}

// SetGroupID sets the "group_id" field.
func (u *PackageChannelUpsert) SetGroupID(v int64) *PackageChannelUpsert {
	u.Set(packagechannel.FieldGroupID, v)
	return u
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *PackageChannelUpsert) UpdateGroupID() *PackageChannelUpsert {
	u.SetExcluded(packagechannel.FieldGroupID)
	return u
}

// SetAccountID sets the "account_id" field.
func (u *PackageChannelUpsert) SetAccountID(v int64) *PackageChannelUpsert {
	u.Set(packagechannel.FieldAccountID, v)
	return u
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *PackageChannelUpsert) UpdateAccountID() *PackageChannelUpsert {
	u.SetExcluded(packagechannel.FieldAccountID)
	return u
}

// SetWeight sets the "weight" field.
func (u *PackageChannelUpsert) SetWeight(v int) *PackageChannelUpsert {
	u.Set(packagechannel.FieldWeight, v)
	return u
}

// UpdateWeight sets the "weight" field to the value that was provided on create.
func (u *PackageChannelUpsert) UpdateWeight() *PackageChannelUpsert {
	u.SetExcluded(packagechannel.FieldWeight)
	return u
}

// AddWeight adds v to the "weight" field.
func (u *PackageChannelUpsert) AddWeight(v int) *PackageChannelUpsert {
	u.Add(packagechannel.FieldWeight, v)
	return u
}

// SetMaxUsers sets the "max_users" field.
func (u *PackageChannelUpsert) SetMaxUsers(v int) *PackageChannelUpsert {
	u.Set(packagechannel.FieldMaxUsers, v)
	return u
}

// UpdateMaxUsers sets the "max_users" field to the value that was provided on create.
func (u *PackageChannelUpsert) UpdateMaxUsers() *PackageChannelUpsert {
	u.SetExcluded(packagechannel.FieldMaxUsers)
	return u
}

// AddMaxUsers adds v to the "max_users" field.
func (u *PackageChannelUpsert) AddMaxUsers(v int) *PackageChannelUpsert {
	u.Add(packagechannel.FieldMaxUsers, v)
	return u
}

// SetIsEnabled sets the "is_enabled" field.
func (u *PackageChannelUpsert) SetIsEnabled(v bool) *PackageChannelUpsert {
	u.Set(packagechannel.FieldIsEnabled, v)
	return u
}

// UpdateIsEnabled sets the "is_enabled" field to the value that was provided on create.
func (u *PackageChannelUpsert) UpdateIsEnabled() *PackageChannelUpsert {
	u.SetExcluded(packagechannel.FieldIsEnabled)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.PackageChannel.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *PackageChannelUpsertOne) UpdateNewValues() *PackageChannelUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(packagechannel.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.PackageChannel.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *PackageChannelUpsertOne) Ignore() *PackageChannelUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PackageChannelUpsertOne) DoNothing() *PackageChannelUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PackageChannelCreate.OnConflict
// documentation for more info.
func (u *PackageChannelUpsertOne) Update(set func(*PackageChannelUpsert)) *PackageChannelUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PackageChannelUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PackageChannelUpsertOne) SetUpdatedAt(v time.Time) *PackageChannelUpsertOne {
	return u.Update(func(s *PackageChannelUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PackageChannelUpsertOne) UpdateUpdatedAt() *PackageChannelUpsertOne {
	return u.Update(func(s *PackageChannelUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetGroupID sets the "group_id" field.
func (u *PackageChannelUpsertOne) SetGroupID(v int64) *PackageChannelUpsertOne {
	return u.Update(func(s *PackageChannelUpsert) {
		s.SetGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *PackageChannelUpsertOne) UpdateGroupID() *PackageChannelUpsertOne {
	return u.Update(func(s *PackageChannelUpsert) {
		s.UpdateGroupID()
	})
}

// SetAccountID sets the "account_id" field.
func (u *PackageChannelUpsertOne) SetAccountID(v int64) *PackageChannelUpsertOne {
	return u.Update(func(s *PackageChannelUpsert) {
		s.SetAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *PackageChannelUpsertOne) UpdateAccountID() *PackageChannelUpsertOne {
	return u.Update(func(s *PackageChannelUpsert) {
		s.UpdateAccountID()
	})
}

// SetWeight sets the "weight" field.
func (u *PackageChannelUpsertOne) SetWeight(v int) *PackageChannelUpsertOne {
	return u.Update(func(s *PackageChannelUpsert) {
		s.SetWeight(v)
	})
}

// AddWeight adds v to the "weight" field.
func (u *PackageChannelUpsertOne) AddWeight(v int) *PackageChannelUpsertOne {
	return u.Update(func(s *PackageChannelUpsert) {
		s.AddWeight(v)
	})
}

// UpdateWeight sets the "weight" field to the value that was provided on create.
func (u *PackageChannelUpsertOne) UpdateWeight() *PackageChannelUpsertOne {
	return u.Update(func(s *PackageChannelUpsert) {
		s.UpdateWeight()
	})
}

// SetMaxUsers sets the "max_users" field.
func (u *PackageChannelUpsertOne) SetMaxUsers(v int) *PackageChannelUpsertOne {
	return u.Update(func(s *PackageChannelUpsert) {
		s.SetMaxUsers(v)
	})
}

// AddMaxUsers adds v to the "max_users" field.
func (u *PackageChannelUpsertOne) AddMaxUsers(v int) *PackageChannelUpsertOne {
	return u.Update(func(s *PackageChannelUpsert) {
		s.AddMaxUsers(v)
	})
}

// UpdateMaxUsers sets the "max_users" field to the value that was provided on create.
func (u *PackageChannelUpsertOne) UpdateMaxUsers() *PackageChannelUpsertOne {
	return u.Update(func(s *PackageChannelUpsert) {
		s.UpdateMaxUsers()
	})
}

// SetIsEnabled sets the "is_enabled" field.
func (u *PackageChannelUpsertOne) SetIsEnabled(v bool) *PackageChannelUpsertOne {
	return u.Update(func(s *PackageChannelUpsert) {
		s.SetIsEnabled(v)
	})
}

// UpdateIsEnabled sets the "is_enabled" field to the value that was provided on create.
func (u *PackageChannelUpsertOne) UpdateIsEnabled() *PackageChannelUpsertOne {
	return u.Update(func(s *PackageChannelUpsert) {
		s.UpdateIsEnabled()
	})
}

// Exec executes the query.
func (u *PackageChannelUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PackageChannelCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PackageChannelUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *PackageChannelUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *PackageChannelUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// PackageChannelCreateBulk is the builder for creating many PackageChannel entities in bulk.
type PackageChannelCreateBulk struct {
	config
	err      error
	builders []*PackageChannelCreate
	conflict []sql.ConflictOption
}

// Save creates the PackageChannel entities in the database.
func (_c *PackageChannelCreateBulk) Save(ctx context.Context) ([]*PackageChannel, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*PackageChannel, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PackageChannelMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PackageChannelCreateBulk) SaveX(ctx context.Context) []*PackageChannel {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PackageChannelCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PackageChannelCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.PackageChannel.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PackageChannelUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *PackageChannelCreateBulk) OnConflict(opts ...sql.ConflictOption) *PackageChannelUpsertBulk {
	_c.conflict = opts
	return &PackageChannelUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.PackageChannel.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *PackageChannelCreateBulk) OnConflictColumns(columns ...string) *PackageChannelUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &PackageChannelUpsertBulk{
		create: _c,
	}
}

// PackageChannelUpsertBulk is the builder for "upsert"-ing
// a bulk of PackageChannel nodes.
type PackageChannelUpsertBulk struct {
	create *PackageChannelCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.PackageChannel.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *PackageChannelUpsertBulk) UpdateNewValues() *PackageChannelUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(packagechannel.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.PackageChannel.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *PackageChannelUpsertBulk) Ignore() *PackageChannelUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PackageChannelUpsertBulk) DoNothing() *PackageChannelUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PackageChannelCreateBulk.OnConflict
// documentation for more info.
func (u *PackageChannelUpsertBulk) Update(set func(*PackageChannelUpsert)) *PackageChannelUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PackageChannelUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PackageChannelUpsertBulk) SetUpdatedAt(v time.Time) *PackageChannelUpsertBulk {
	return u.Update(func(s *PackageChannelUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PackageChannelUpsertBulk) UpdateUpdatedAt() *PackageChannelUpsertBulk {
	return u.Update(func(s *PackageChannelUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetGroupID sets the "group_id" field.
func (u *PackageChannelUpsertBulk) SetGroupID(v int64) *PackageChannelUpsertBulk {
	return u.Update(func(s *PackageChannelUpsert) {
		s.SetGroupID(v)
	})
}

// UpdateGroupID sets the "group_id" field to the value that was provided on create.
func (u *PackageChannelUpsertBulk) UpdateGroupID() *PackageChannelUpsertBulk {
	return u.Update(func(s *PackageChannelUpsert) {
		s.UpdateGroupID()
	})
}

// SetAccountID sets the "account_id" field.
func (u *PackageChannelUpsertBulk) SetAccountID(v int64) *PackageChannelUpsertBulk {
	return u.Update(func(s *PackageChannelUpsert) {
		s.SetAccountID(v)
	})
}

// UpdateAccountID sets the "account_id" field to the value that was provided on create.
func (u *PackageChannelUpsertBulk) UpdateAccountID() *PackageChannelUpsertBulk {
	return u.Update(func(s *PackageChannelUpsert) {
		s.UpdateAccountID()
	})
}

// SetWeight sets the "weight" field.
func (u *PackageChannelUpsertBulk) SetWeight(v int) *PackageChannelUpsertBulk {
	return u.Update(func(s *PackageChannelUpsert) {
		s.SetWeight(v)
	})
}

// AddWeight adds v to the "weight" field.
func (u *PackageChannelUpsertBulk) AddWeight(v int) *PackageChannelUpsertBulk {
	return u.Update(func(s *PackageChannelUpsert) {
		s.AddWeight(v)
	})
}

// UpdateWeight sets the "weight" field to the value that was provided on create.
func (u *PackageChannelUpsertBulk) UpdateWeight() *PackageChannelUpsertBulk {
	return u.Update(func(s *PackageChannelUpsert) {
		s.UpdateWeight()
	})
}

// SetMaxUsers sets the "max_users" field.
func (u *PackageChannelUpsertBulk) SetMaxUsers(v int) *PackageChannelUpsertBulk {
	return u.Update(func(s *PackageChannelUpsert) {
		s.SetMaxUsers(v)
	})
}

// AddMaxUsers adds v to the "max_users" field.
func (u *PackageChannelUpsertBulk) AddMaxUsers(v int) *PackageChannelUpsertBulk {
	return u.Update(func(s *PackageChannelUpsert) {
		s.AddMaxUsers(v)
	})
}

// UpdateMaxUsers sets the "max_users" field to the value that was provided on create.
func (u *PackageChannelUpsertBulk) UpdateMaxUsers() *PackageChannelUpsertBulk {
	return u.Update(func(s *PackageChannelUpsert) {
		s.UpdateMaxUsers()
	})
}

// SetIsEnabled sets the "is_enabled" field.
func (u *PackageChannelUpsertBulk) SetIsEnabled(v bool) *PackageChannelUpsertBulk {
	return u.Update(func(s *PackageChannelUpsert) {
		s.SetIsEnabled(v)
	})
}

// UpdateIsEnabled sets the "is_enabled" field to the value that was provided on create.
func (u *PackageChannelUpsertBulk) UpdateIsEnabled() *PackageChannelUpsertBulk {
	return u.Update(func(s *PackageChannelUpsert) {
		s.UpdateIsEnabled()
	})
}

// Exec executes the query.
func (u *PackageChannelUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the PackageChannelCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PackageChannelCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PackageChannelUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
